name: Automatic Grader

on:
  push:
    branches:
      - main
    paths:
      - '**.Rmd'
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  
  
jobs:
  build:
    name: Grader Jobs
    runs-on: ubuntu-20.04
    if:      ${{ !contains(github.actor,'classroom' )}}
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Checks environment ğŸ“¡
        run: |
           echo ${GITHUB_WORKSPACE}
           echo "-----------------"
           echo ${{github.workspace}}
      - name: Relocate within runner ğŸš§
        run: |
          sed -i "s|local-directory|${{ github.workspace }}|g" .github/classroom/run-grader.sh
          sed -i "s|local-directory|${{ github.workspace }}|g" .github/classroom/run-compiler.sh
      - name: Prepare image ğŸ¤–
        run: |
          docker run -v "${{ github.workspace }}:/home/rstudio" agarbuno/grader:beta R -e 'renv::restore()'
      - name: Grade homework ğŸ’»
        uses: education/autograding@v1
      - name: Add pdf file ğŸ“•
        run: |
          mv entrega.pdf entrega-${{github.actor}}.pdf
          git config --global user.name ${{ github.actor }}
          git add entrega*.pdf
          git commit -m "Agrega entrega a repositorio"
          git push
