name: Docker Build

on:
  push:
    branches:
      - ag/docker-cache
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  
  
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-20.04
    if:      ${{ !contains(github.actor,'classroom' )}}
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Build a docker ğŸ“¡
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: grader
          push_image_and_stages: false
          dockerfile: .tests/Dockerfile
      - name: Checks R version ğŸ’»
        run: |
          docker run \
          grader:latest R --version
          
      # - name: Checks R version ğŸ’»
      #   run: R --version
      # - name: Cache packages ğŸ“±
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ env.RENV_PATHS_ROOT }}
      #     key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-renv-
      # - name: Restore packages ğŸ›–
      #   shell: Rscript {0}
      #   run: |
      #     if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
      #     renv::restore()
      # - name: Grade homework ğŸ“š
      #   uses: education/autograding@v1
