name: Docker Build

on:
  push:
    branches:
      - ag/docker-build

permissions:
  checks: write
  actions: read
  contents: read

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  
  
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-20.04
    if:      ${{ !contains(github.actor,'classroom' )}}
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Get a docker ğŸ“¡
        run: docker pull agarbuno/env-simulacion
      - name: Say Hello!
        run: |
          docker run -it agarbuno/env-simulacion /bin/echo "Hello world"
      # - name: Checks R version ğŸ’»
      #   run: R --version
      # - name: Cache packages ğŸ“±
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ env.RENV_PATHS_ROOT }}
      #     key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-renv-
      # - name: Restore packages ğŸ›–
      #   shell: Rscript {0}
      #   run: |
      #     if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
      #     renv::restore()
      # - name: Grade homework ğŸ“š
      #   uses: education/autograding@v1
