name: Grade homework 
on:
  push:
    branches:
      - main  
permissions:
  contents: write
      
jobs:
  checkout:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Freezes R version ğŸ’»
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.1' # The R version to download (if necessary) and use.
      - name: Checks R version ğŸ’»
        run: R --version
      - name: Install libcurl ğŸ’» 
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev 
      - name: Cache packages ğŸ“±
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages ğŸ›–
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      # Use GitHub Actions' cache to cache dependencies on servers
      # - name: Cache ğŸªµ
      #   uses: actions/cache@v2
      #   with:
      #     path: vendor/bundle
      #     key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gems-
