name: Grade homework 
on:
  push:
    branches:
      - main  
permissions:
  contents: write
      
jobs:
  # Let's configure the system
  system_setup:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Freezes R version ğŸ’»
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.1' # The R version to download (if necessary) and use.
      - name: Checks R version ğŸ’»
        run: R --version
      - name: Install libcurl ğŸ’» 
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev 
      - name: Cache packages ğŸ“±
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages ğŸ›–
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
  # Let's grade your homework
  grade_homework:
    runs-on: ubuntu-latest
    needs: system_setup
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Grade homework ğŸ“š
        run: testthat::test_dir('.tests/testthat/')
        shell: Rscript {0}
